services:
  - type: web
    name: distillery-management-software
    env: python
    plan: free
    branch: master
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn distillery_core.wsgi
    envVars:
      - key: postgresql://postgres.hysycjjcirvjrvzgzesg:Machenna!1@aws-0-us-west-1.pooler.supabase.com:6543/postgres
        fromDatabase:
          name: distillery-core-db
          property: connectionString
      - key: SECRET_KEY
        value: my-secret-12345
      - key: DEBUG
        value: False
databases:
  - name: distillery-core-db