services:
  - type: web
    name: distillery-management-software
    env: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn distillery_core.wsgi
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.jyarhjszfqupunckzisk:Machenna!1@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - key: SECRET_KEY
        value: my-secret-12345
      - key: DEBUG
        value: False
      - key: PYTHONPATH
        value: /app:/app/distillery_core